name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g netlify-cli
        
    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        netlify deploy --prod --dir=.
        
    - name: Force HTTPS
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"force_ssl": true}' \
          https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/ssl 